---

- src: openmicroscopy.postgresql
  version: 3.0.1

- src: openmicroscopy.omero-common
  version: 0.3.0

- name: openmicroscopy.omego
  version: 0.1.1

- name: openmicroscopy.omero-server
  version: 2.0.3

- name: openmicroscopy.omero-web
  version: 1.0.2

- name: omero-user
  version: 0.1.1
